// Crear productos deportivos
const products = [
  {id: 1, name: 'Peluche abeja', price:36000,img: './image/abeja.jpeg', categoria: "Peluches"},
  {id: 2, name: 'Gorro Cinnamoroll', price:38000,img: './image/cinamonroll.jpeg', categoria: "Accesorios"},
  {id: 3, name: 'Peluche Hello Kitty', price:30000,img: './image/hellokitty.jpeg', categoria: "Peluches"},
  {id: 4, name: 'Frog Gorro', price:38000,img: './image/bucketRana.jpeg', categoria: "Accesorios"},
  {id: 5, name: 'Peluche Ballena', price:36000,img: './image/ballena.jpeg', categoria: "Peluches"},
  {id: 6, name: 'Bucket hat Frog crochet', price:40000,img: './image/gorroRana.jpeg', categoria: "Accesorios"},
  {id: 7, name: 'Peluche conejo bicolor', price:45000,img: './image/conejoBicolor.jpeg', categoria: "Peluches"},
  {id: 8, name: 'Top Antonella', price:38000,img: './image/top.jpeg', categoria: "Tops"},
  {id: 9, name: 'Peluche mapache Winnie', price:48000,img: './image/mapache.jpeg', categoria: "Peluches"},
  {id: 10, name: 'Top Lola', price: 40000,img: './image/topLola.jpeg', categoria: "Tops"},
  {id: 11, name: 'Peluche conejo rosa', price:48000,img: './image/conejoRosa.jpeg', categoria: "Peluches"},
  {id: 12, name: 'Cardigan Daisy', price:80000,img: './image/cardiganFlor.jpeg', categoria: "Cardigan"},
  {id: 13, name: 'Peluche paquita la gallina', price:28000,img: './image/gallina.jpeg', categoria: "Peluches"},
  {id: 14, name: 'Flor girasol', price:16000,img: './image/girasol.jpeg', categoria: "Accesorios"},
  {id: 15, name: 'Peluche vaquita Lucy', price:48000,img: './image/vaquita.jpeg', categoria: "Peluches"},
  {id: 16, name: 'Top Bella', price:40000,img: './image/topBella.jpeg', categoria: "Tops"},
  {id: 17, name: 'Peluche ajolote', price:30000,img: './image/ajolote.jpeg', categoria: "Peluches"},
  {id: 18, name: 'Cardigan JW Anderson', price:120000,img: './image/cardiganHarry.jpeg', categoria: "Cardigan"},
  {id: 19, name: 'Peluche conejo Thomas', price:48000,img: './image/conejoGafas.jpeg', categoria: "Peluches"},
  {id: 20, name: 'Summer Top', price:50000,img: './image/summerTop.jpeg', categoria: "Tops"},
  {id: 21, name: 'Bucket hat Daisy', price:35000,img: './image/bucket.jpeg', categoria: "Accesorios"},
  {id: 22, name: 'Aretes de cereza', price:12000,img: './image/cereza.jpeg', categoria: "Accesorios"},
  {id: 23, name: 'Peluche pollito', price:28000,img: './image/pollito.jpeg', categoria: "Peluches"},
  {id: 24, name: 'Harper Top', price:45000,img: './image/harperTop.jpeg', categoria: "Tops"},
  {id: 25, name: 'Peluche de Hongo', price:45000,img: './image/hongo.jpeg', categoria: "Peluches"},
  {id: 26, name: 'Top Marcella', price:50000,img: './image/topSencillo.jpeg', categoria: "Tops"},
  {id: 27, name: 'Peluche tortuga Daisy', price:40000,img: './image/tortuga.jpeg', categoria: "Peluches"},
  {id: 28, name: 'Bolso Daisy', price:40000,img: './image/bolosFlor.jpeg', categoria: "Accesorios"},
  {id: 29, name: 'Conejo Strawberry', price:48000,img: './image/conejoFresa.jpeg', categoria: "Peluches"},
  {id: 30, name: 'Cardigan Clasic', price:200000,img: './image/Cardigan clasic.jpeg', categoria: "Cardigan"},
  {id: 31, name: 'Cardigan Estella', price:170000,img: './image/Cardigan Estella.jpeg', categoria: "Cardigan"},
  {id: 30, name: 'Top Camila', price:40000,img: './image/Top Camila.jpeg', categoria: "Tops"},
  {id: 32, name: 'Cardigan Flowers', price:170000,img: './image/Cardigan Flowers.jpeg', categoria: "Cardigan"},
  {id: 32, name: 'Peluche sun vaquita', price:45000,img: './image/Peluche Vaquita Sun.jpeg', categoria: "Peluches"},
  {id: 33, name: 'Cardigan Happy Face', price:130000,img: './image/Cardigan happy face.jpeg', categoria: "Cardigan"},
];